# acoes_fatores.py

_DEFAULT_ACOES = [
    {
        "numero": 1,
        "fator": "Trabalho sem pausas para descanso",
        "acao_baixo": "Manter e reforçar a política de pausas já adotada, garantindo que continue efetiva.",
        "acao_moderado": "Avaliar se as pausas estão sendo respeitadas e propor ajustes em casos pontuais.",
        "acao_elevado": "Revisar a política de pausas para ampliar a frequência e garantir o descanso necessário.",
        "acao_critico": "Implementar imediatamente pausas regulares e obrigatórias, com fiscalização da aplicação.",
    },
    {
        "numero": 2,
        "fator": "Ritmo intenso de trabalho",
        "acao_baixo": "Manter o ritmo de trabalho atual e monitorar continuamente.",
        "acao_moderado": "Reduzir prazos excessivos e revisar metas para equilibrar ritmo e qualidade.",
        "acao_elevado": "Reorganizar a distribuição de tarefas para evitar sobrecarga e acelerar fluxos de trabalho.",
        "acao_critico": "Ajustar urgentemente o modelo de produção para reduzir o ritmo excessivo e prevenir danos à saúde.",
    },
    {
        "numero": 3,
        "fator": "Variação de turnos",
        "acao_baixo": "Manter o modelo de turnos atual e acompanhar os impactos.",
        "acao_moderado": "Reduzir variações de turnos e garantir previsibilidade aos colaboradores.",
        "acao_elevado": "Realinhar a escala de turnos, evitando alternâncias frequentes e priorizando estabilidade.",
        "acao_critico": "Reestruturar o sistema de turnos com foco em estabilidade e saúde dos colaboradores.",
    },
    {
        "numero": 4,
        "fator": "Capacidade insuficiente para as tarefas",
        "acao_baixo": "Manter a compatibilidade entre habilidades e demandas das tarefas.",
        "acao_moderado": "Oferecer treinamentos pontuais e ajustar expectativas de desempenho.",
        "acao_elevado": "Aplicar plano de capacitação contínua para adequar competências às exigências.",
        "acao_critico": "Redefinir urgentemente as atribuições ou realocar colaboradores para funções adequadas.",
    },
    {
        "numero": 5,
        "fator": "Metas rigorosas",
        "acao_baixo": "Manter metas desafiadoras e atingíveis, com acompanhamento equilibrado.",
        "acao_moderado": "Revisar metas e estabelecer limites mais realistas conforme o contexto.",
        "acao_elevado": "Negociar metas setoriais com participação ativa dos colaboradores.",
        "acao_critico": "Suspender metas abusivas e reconstruir o planejamento com foco em saúde ocupacional.",
    },
    {
        "numero": 6,
        "fator": "Trabalho remunerado por produção",
        "acao_baixo": "Manter o modelo atual com acompanhamento de indicadores de saúde.",
        "acao_moderado": "Revisar a política de remuneração considerando variações de produtividade por setor.",
        "acao_elevado": "Reduzir o peso da produção na remuneração, priorizando equilíbrio e bem-estar.",
        "acao_critico": "Suspender o modelo de remuneração por produção e reestruturar o sistema de incentivos.",
    },
    {
        "numero": 7,
        "fator": "Desequilíbrio trabalho x descanso",
        "acao_baixo": "Preservar o equilíbrio atual entre trabalho e tempo de recuperação.",
        "acao_moderado": "Estimular boas práticas de descanso e limites de jornada.",
        "acao_elevado": "Adequar a carga horária e ampliar períodos de descanso, inclusive entre jornadas.",
        "acao_critico": "Interromper jornadas excessivas e garantir cumprimento integral da legislação trabalhista.",
    },
    {
        "numero": 8,
        "fator": "Situações de estresse",
        "acao_baixo": "Manter programas de apoio emocional e monitorar o clima organizacional.",
        "acao_moderado": "Promover atividades de bem-estar e controle de estresse no ambiente de trabalho.",
        "acao_elevado": "Implantar políticas preventivas e grupos de apoio psicológico.",
        "acao_critico": "Ação emergencial com suporte profissional especializado e revisão estrutural dos fatores estressores.",
    },
    {
        "numero": 9,
        "fator": "Sobrecarga mental",
        "acao_baixo": "Manter níveis adequados de exigência mental e complexidade das tarefas.",
        "acao_moderado": "Simplificar procedimentos e revisar rotinas sobrecarregadas.",
        "acao_elevado": "Reduzir a densidade de tarefas simultâneas e implantar pausas cognitivas.",
        "acao_critico": "Redefinir o conteúdo das tarefas e reestruturar setores com alta carga cognitiva imediata.",
    },
    {
        "numero": 10,
        "fator": "Exigência cognitiva elevada",
        "acao_baixo": "Manter desafios intelectuais proporcionais às capacidades da equipe.",
        "acao_moderado": "Fornecer ferramentas de apoio e capacitação cognitiva.",
        "acao_elevado": "Reduzir o número de processos complexos simultâneos no setor.",
        "acao_critico": "Redefinir processos mentais complexos e aplicar rodízio funcional.",
    },
    {
        "numero": 11,
        "fator": "Comunicação deficiente",
        "acao_baixo": "Manter canais de comunicação claros e acessíveis.",
        "acao_moderado": "Mapear falhas e melhorar fluxos de informação entre áreas.",
        "acao_elevado": "Reestruturar a comunicação formal e informal com foco em clareza e efetividade.",
        "acao_critico": "Implementar um plano de comunicação interna com urgência, com capacitação de líderes.",
    },
    {
        "numero": 12,
        "fator": "Conflitos no trabalho",
        "acao_baixo": "Manter ambiente cooperativo e com baixa incidência de conflitos.",
        "acao_moderado": "Promover mediação pontual e diálogo entre as partes envolvidas.",
        "acao_elevado": "Implantar comissões ou núcleos de resolução de conflitos e treinamentos.",
        "acao_critico": "Intervenção organizacional urgente com mediação profissional e medidas disciplinares.",
    },
    {
        "numero": 13,
        "fator": "Demandas emocionais/afetivas",
        "acao_baixo": "Manter suporte emocional e acolhimento.",
        "acao_moderado": "Ampliar a escuta ativa e treinamentos em inteligência emocional.",
        "acao_elevado": "Oferecer assistência emocional com profissionais da área de saúde mental.",
        "acao_critico": "Apoio institucional formal com equipe multiprofissional e afastamento temporário quando necessário.",
    },
    {
        "numero": 14,
        "fator": "Assédio no trabalho",
        "acao_baixo": "Manter política de tolerância zero e canais acessíveis de denúncia.",
        "acao_moderado": "Reforçar campanhas de prevenção e protocolos de apuração.",
        "acao_elevado": "Implementar treinamentos obrigatórios sobre assédio e ética profissional.",
        "acao_critico": "Ação imediata com apuração rigorosa, responsabilização e suporte às vítimas.",
    },
    {
        "numero": 15,
        "fator": "Demandas divergentes",
        "acao_baixo": "Manter alinhamento claro entre diferentes demandas e setores.",
        "acao_moderado": "Identificar pontos de divergência e propor ajustes entre departamentos.",
        "acao_elevado": "Redefinir processos de decisão com foco em coerência entre ordens e metas.",
        "acao_critico": "Reestruturação urgente dos fluxos de comando e revisão de diretrizes organizacionais.",
    },
    {
        "numero": 16,
        "fator": "Multitarefas com alta carga cognitiva",
        "acao_baixo": "Manter equilíbrio entre tarefas simultâneas e pausas mentais.",
        "acao_moderado": "Reduzir número de multitarefas simultâneas por colaborador.",
        "acao_elevado": "Redefinir atividades para distribuição mais racional e foco unitário.",
        "acao_critico": "Suspender rotinas multitarefas com sobrecarga cognitiva imediata e revisar funções.",
    },
    {
        "numero": 17,
        "fator": "Insatisfação no trabalho",
        "acao_baixo": "Manter ações de valorização e escuta ativa contínuas.",
        "acao_moderado": "Investigar causas de insatisfação e propor melhorias pontuais.",
        "acao_elevado": "Rever políticas internas e clima organizacional com participação dos colaboradores.",
        "acao_critico": "Intervenção urgente com plano estratégico de valorização e motivação.",
    },
    {
        "numero": 18,
        "fator": "Falta de autonomia",
        "acao_baixo": "Manter nível atual de autonomia com acompanhamento.",
        "acao_moderado": "Expandir a participação dos colaboradores nas decisões do setor.",
        "acao_elevado": "Revisar processos que limitam a autonomia e implantar gestão mais participativa.",
        "acao_critico": "Reestruturar imediatamente a gestão do setor para garantir autonomia real e efetiva.",
    }
]
