# Generated by Django 5.2.4 on 2025-07-15 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_logacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='classificacao',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado'), ('Crítico', 'Crítico')], default='Baixo', help_text='Classificação da ação conforme o risco', max_length=10),
        ),
        migrations.AddField(
            model_name='fator',
            name='classificacao_risco',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado'), ('Crítico', 'Crítico')], default='Baixo', help_text='Classificação do risco deste fator', max_length=10),
        ),
        migrations.AlterField(
            model_name='fator',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logacao',
            name='acao',
            field=models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('login', 'Login'), ('logout', 'Logout')], help_text='Tipo de ação executada', max_length=20),
        ),
        migrations.AlterField(
            model_name='logacao',
            name='executado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_executadas_painel', to=settings.AUTH_USER_MODEL),
        ),
    ]
