# Generated by Django 5.2.4 on 2025-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_acao_classificacao_fator_classificacao_risco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fator',
            name='ordem',
            field=models.PositiveIntegerField(default=9999, help_text='Número fixo para ordenar os fatores de 1 a 18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acao',
            name='classificacao',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado'), ('Crítico', 'Crítico')], default='Baixo', help_text='Classificação da ação conforme o risco que ela atende', max_length=10),
        ),
        migrations.AlterField(
            model_name='fator',
            name='classificacao_risco',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Elevado', 'Elevado'), ('Crítico', 'Crítico')], default='Baixo', help_text='Classificação do risco deste fator (calculada a partir das respostas)', max_length=10),
        ),
    ]
