# Generated by Django 5.2.4 on 2025-07-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_fator_ordem_alter_acao_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fator',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterField(
            model_name='fator',
            name='ordem',
            field=models.PositiveIntegerField(help_text='Número fixo para ordenar os fatores de 1 a 18', unique=True),
        ),
    ]
