# Generated by Django 5.2.4 on 2025-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_alter_pergunta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número sequencial da pergunta para ordenar e controlar a sequência', unique=True),
        ),
    ]
