# Generated by Django 5.2.4 on 2025-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_alter_pergunta_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Texto Diagnóstico', max_length=100)),
                ('bloco_1', models.TextField(blank=True, verbose_name='Bloco Inicial do Diagnóstico')),
                ('bloco_2', models.TextField(blank=True, verbose_name='Bloco Final do Diagnóstico')),
            ],
        ),
    ]
