# Generated by Django 5.2.4 on 2025-07-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome_setor'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='funcionarios',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='nome',
        ),
        migrations.AddField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(default='Setor Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='num_funcionarios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
