# Generated by Django 5.2.4 on 2025-07-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.setor'),
        ),
    ]
