# Generated by Django 5.2.4 on 2025-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='funcionarios',
        ),
        migrations.AddField(
            model_name='setor',
            name='num_funcionarios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
